### ISSUE TITLE
No support for OpenAPI 3.1.0 specs

### ISSUE THREAD

**Issue by mrsafalpiya** [japa/assert#4]
### Package version

3.0.0

## What

Currently the OpenAPI  3.1.0 specs is not supported.

## Cause

`@japa/assert 3.0.0` depends upon `api-contract-validator ^2.2.8` which depends upon `api-schema-builder ^2.0.10` which depends upon `openapi-schema-validator ^3.0.3` (which is based on this commit from 2019-01-31: https://github.com/kogosoftwarellc/open-api/commit/2781e855aa5f42db84ab02e0ac9803bfffeb7f3e#diff-70c35980076f3148e728c8457dc8dc282a65872bbe4d51aec3a13282775e7fcdR7)

For context 3.1.0 spec was released in 2021-02-15.

## Fix (Not viable)

Make `api-schema-builder` use `openapi-schema-validator v12.1.3`  fully supports OpenApi 3.1.0. This is not viable as both `api-contract-validator` and `api-schema-builder` seem to be abandoned.

**Comment by thetutlage** [comment]
I don't have the bandwidth right now to work on this issue. If anyone feels like opening a PR, feel free to do it :)

**Comment by mrsafalpiya** [comment]
I found a temporary fix by using the `overrides` fields in `package.json` as:

```json
  "overrides": {
    "api-schema-builder": {
      "openapi-schema-validator": "^12.1.3"
    }
  },
````

Maybe mention it in docs till a proper fix comes along? 🤷

**Comment by josevelaz** [comment]
This was also causing issues with npm ci within containerized environments
https://github.com/japa/assert/issues/3

**Comment by thetutlage** [comment]
Fixed by https://github.com/japa/assert/pull/5

It will be moved to its own plugin. However, we still can't fix the transitive dependencies of that package
